---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kort-secret
  namespace: kort
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCkoztjiDlg6rjPvuZQta4izNWFrkj3EOm6XWD6pbVQrhFw+9wv0OFVR7jfKLR/RzY7pSxPaRSfDn7oMgnaqWiOvEjJqBefc2sqWAgYshqCZVITwzQ78GaOw6/ewIAqInhouZIvFfKXDofBrPQZHqHqZCt60Ytndr6v8iYiFVX6yom2N3JttzKQas+Prjgx5rh3whKhttTKbZGRZBmBNwa8Ss6G+QPVuCvxmSeB9J0xaUoO37SYqOeRUIrcBmBNVW+QuOETCTXhSvz/LR9vp26OpZ7JQ5kn2nbZYDiEw2izxIIciujE+IipP4PPpBs8Nz0bB9b/R9Q2mQBKhLu8AjVduB4xlbY3hRzQnnEnEY6pbhx3ID+gFlIdIaRWxMWgYnrksDCtJOlmgvZSlYlluDXBqW5XKcRGqSBLxQrOlr8G8mAiUlWOzEiTPiaUIojLAD7J+Wt1zqutVMS9LGme/b/UqteKamBWg7IU2a2n9Z8H71RxAUiQnr92FbI7epf4ius5IC+wW2yARThKtxSmZyVhs7ymFLU/IKFDyRgCmczemy2eylAwn35wcOMv7ZjkBK/QtkoRhq16VH6vNBjYRK7n3uQwuiPaieaJ1y1hwtk09v8VG/j3/6xNQYO6xnHL7czyBbjGLwtT2XzHdxPrTrmf1+0bjwWDRRNjGH+V3L7VwfMR/9167UAfxXNpLfaeiXTceOr//zxTWraSioxcxG4=
    POSTGRES_USER: AgB0lFInAfOlGRNr7zk0GjiV7czmnTuX1Yk1DyQOCwHVdPGEhSVoNQt8GGahKzS6s6oorK9WYkC/2g9llCfY8Dxhl1AIK9qyVNpskumrb023HdMavtXE3mVbaIoFTJsuvyfO8biA8VDH+cgtpma9I199WIl7i+JXm2evqN3uzPj9R9E3X9RWOWDxuTYluaVmKT1VNMHb6QBhUFk2VkCMPr/1h/jo661O7eA6PaciWd4l0wTKGdRG0JvkB+XiZsinCCRN7mG6eqb9BFXKlCO/OpSdDA1iN/vP8Mv9moz8l44XzbHgaULARhAqEmEwJcsP/qtw5Ji/OtQ0YFQjn5s1uADmfJlnd8oO+prke6z8s0X2ZyoC/Z0JwOI+BNvTXoDZwpa6SBbO8b5cq77mx25nPYg7Ds93RAAvPrPKqQOrqGaZJE4DFDJHQA0KglPlrb8dHCShSmyxAIMvqkLFC9h2KLgKmfQlk+jLkTMUAayT5x7PJM5BdtRJ4NAa6UEE0T/+3Jv0JvrufD/C6EuHFyc90tyHNv/FO6oAfLSBP7rV74QQS4mt9OpKSGAYsAGGBQp/4ZGD0VVSehyYNpXGyguU0fxBC3lzDYHxXSJOkPbP3E/ntm1VqdSoYc16GuuuLSqQtxgsBU13Ew5g2IL+Ygnp7t3Ok6Qw+4QPcWs4aRLm81W6zTP4Q71jqOAyRp2vKfXwFqrO3lFIaW8kepPoenQS
  template:
    metadata:
      name: kort-secret
      namespace: kort
    type: Opaque
