apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: kort

images:
  - name: kimtsr/kort-api
    newTag: "1.0"

  - name: kimtsr/kort-cleaner
    newTag: "1.0"

  - name: kimtsr/kort-web
    newTag: "1.0"

  - name: kimtsr/kort-worker
    newTag: "1.0"
