apiVersion: v1
kind: ConfigMap
metadata:
  name: kort-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  POSTGRES_DB: "kort"
  REDIS_URL: "redis://redis:6379/0"
  CLICK_STREAM: "clicks"
  CLICK_GROUP: "aggregators"
