apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kim-tsr/kort-k3s-deployment
    targetRevision: master
    path: argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: kort
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
