apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: kimtsr/kort-api:1.0
          envFrom:
            - configMapRef:
                name: kort-config
            - secretRef:
                name: kort-secret
          ports:
            - containerPort: 8000
              name: api
