apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleaner
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 5
      template:
        spec:
          containers:
            - name: cleaner
              image: kimtsr/kort-cleaner:1.0
              envFrom:
                - configMapRef:
                    name: kort-config
                - secretRef:
                    name: kort-secret
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  memory: 128Mi
          restartPolicy: Never
